export const districts =[
    {
      "id":"1",
      "title":"trivandrum",
      "image":"https://assets-news.housing.com/news/wp-content/uploads/2022/08/19025232/TRIVANDRUM-FEATURE-compressed.jpg"
    },
    {
      "id":"2",
      "title":"kollam",
      "image":"https://assets-news.housing.com/news/wp-content/uploads/2022/08/19025232/TRIVANDRUM-FEATURE-compressed.jpg"
    },
    {
      "id":"3",
      "title":"pathanamthitta",
      "image":"https://assets-news.housing.com/news/wp-content/uploads/2022/08/19025232/TRIVANDRUM-FEATURE-compressed.jpg"
    },
    {
      "id":"4",
      "title":"alapuzha",
      "image":"https://assets-news.housing.com/news/wp-content/uploads/2022/08/19025232/TRIVANDRUM-FEATURE-compressed.jpg"
    },
    {
      "id":"5",
      "title":"kottayam",
      "image":"https://assets-news.housing.com/news/wp-content/uploads/2022/08/19025232/TRIVANDRUM-FEATURE-compressed.jpg"
    },
    {
      "id":"6",
      "title":"idukki",
      "image":"https://assets-news.housing.com/news/wp-content/uploads/2022/08/19025232/TRIVANDRUM-FEATURE-compressed.jpg"
    },
    {
      "id":"7",
      "title":"ernakulam",
      "image":"https://assets-news.housing.com/news/wp-content/uploads/2022/08/19025232/TRIVANDRUM-FEATURE-compressed.jpg"
    },
    {
      "id":"8",
      "title":"thrissur",
      "image":"https://assets-news.housing.com/news/wp-content/uploads/2022/08/19025232/TRIVANDRUM-FEATURE-compressed.jpg"
    },
    {
      "id":"9",
      "title":"palakadu",
      "image":"https://assets-news.housing.com/news/wp-content/uploads/2022/08/19025232/TRIVANDRUM-FEATURE-compressed.jpg"
    },
    {
      "id":"10",
      "title":"malapuram",
      "image":"https://assets-news.housing.com/news/wp-content/uploads/2022/08/19025232/TRIVANDRUM-FEATURE-compressed.jpg"
    },
    {
      "id":"11",
      "title":"kozhikode",
      "image":"https://assets-news.housing.com/news/wp-content/uploads/2022/08/19025232/TRIVANDRUM-FEATURE-compressed.jpg"
    },
    {
      "id":"12",
      "title":"wayandu",
      "image":"https://assets-news.housing.com/news/wp-content/uploads/2022/08/19025232/TRIVANDRUM-FEATURE-compressed.jpg"
    },
   
    {
      "id":"13",
      "title":"kannur",
      "image":"https://assets-news.housing.com/news/wp-content/uploads/2022/08/19025232/TRIVANDRUM-FEATURE-compressed.jpg",
    },
    {
      "id":"14",
      "title":"kasargode",
      "image":"https://assets-news.housing.com/news/wp-content/uploads/2022/08/19025232/TRIVANDRUM-FEATURE-compressed.jpg"
    },
    {
    
    },
    {},
  ]


