export const districts =[
    {
      "id":"1",
      "title":"trivandrum",
      "image":"./assets/images/trivandrum.jpg",
      "button":"Explore",
    },
    {
      "id":"2",
      "title":"kollam",
      "image":"./assets/images/kollam.jpg",
      "button":"Explore",
    },
    {
      "id":"3",
      "title":"pathanamthitta",
      "image":"./assets/images/pathanamthitta.jpg",
       "button":"Explore",
    },
    {
      "id":"4",
      "title":"alapuzha",
      "image":"./assets/images/alappuzha.jpg",
      "button":"Explore",
    },
    {
      "id":"5",
      "title":"kottayam",
      "image":"./assets/images/kottayam.jpg",
      "button":"Explore",
    },
    {
      "id":"6",
      "title":"idukki",
      "image":"./assets/images/idukki.jpg",
      "button":"Explore",
    },
    {
      "id":"7",
      "title":"ernakulam",
      "image":"./assets/images/ernakulam.jpg",
      "button":"Explore",
    },
    {
      "id":"8",
      "title":"thrissur",
      "image":"./assets/images/thrissur.jpg",
      "button":"Explore",
    },
    {
      "id":"9",
      "title":"palakadu",
      "image":"./assets/images/palakkad.jpg",
      "button":"Explore",
    },
    {
      "id":"10",
      "title":"malapuram",
      "image":"./assets/images/malappuram.jpg",
      "button":"Explore",
    },
    {
      "id":"11",
      "title":"kozhikode",
      "image":"./assets/images/kozhikode.jpg",
      "button":"Explore",
    },
    {
      "id":"12",
      "title":"wayandu",
      "image":"./assets/images/wayanad.jpg",
      "button":"Explore",
    },
   
    {
      "id":"13",
      "title":"kannur",
      "image":"./assets/images/kannur.jpg",
      "button":"Explore",
    },
    {
      "id":"14",
      "title":"kasargode",
      "image":"./assets/images/kasargod.jpg",
      "button":"Explore",
    }
  ]


